### ISSUE TITLE
Add dates?

### ISSUE THREAD

**Issue by kathachanda** [hindupuravinash/the-gan-zoo#10]
Hey, this is super useful, but in a quick glance if I'm looking for something that came out only in (let's say), the last 2 years, it'd be more informative to add the years of release next to the names as well! 
But an awesome job with this!

**Comment by bgavran** [comment]
I agree and to expand: it'd be cool have different sorting methods (sort by date, number of citations). But I'm not sure how realistic the proposal is.

**Comment by kathachanda** [comment]
I didn’t mean you sort it differently. But I guess it’s reasonable to do something like - 

DC-GAN (20xx)
Conditional GAN (20yy) 

And so on, and keep them sorted in alphabetical order. 


Regards,
Katha Chanda

**Comment by pwaller** [comment]
One other possible useful way sorting would be to simply group them by year. Or alternatively to maintain multiple lists in the repository in different documents.

**Comment by hindupuravinash** [comment]
@kathachanda Thanks for compliments :) The suggestion to add years sounds good to me too, can add them in the format you propose. Name - Title ( Year ) Example: GAN - Generative Adversarial Networks (2014)

@pwaller @bgavran Sorting the list is something that I wanted to do right from the beginning, but within markdown is not possible unless the readers install some third party plugins. Other than year and citations, I would like to add links to code implementations, status if selected for ICLR etc to the list! But I couldn't come up with a decent format like a sortable table for the list which would make it easy to read.

**Comment by pwaller** [comment]
Here's an example of how it might look. I just took the dates in the arxiv URL, and sorted by date.

https://github.com/pwaller/the-gan-zoo/tree/put-in-table

**Comment by hindupuravinash** [comment]
@pwaller This does jumble the alphabetic order of the papers. As you suggested, we can put this date sorted list in a separate .md apart from the original alphabetically sorted list. Would that be better?

**Comment by lgalke** [comment]
I also gave github's `.csv`/`.tsv` support a try. @hindupuravinash : it is searchable!

https://github.com/lgalke/the-gan-zoo/blob/master/gans.tsv

However, the links are not clickable anymore, and I have no idea how you could trick github's tsv support to display links (maybe `<a>` would work?).

I'd prefer some kind of hierarchy where the top level sorting order are years (maybe just as headers) and the lower levels are either alphabetically or month, alphabetically.

**Comment by hindupuravinash** [comment]
@lgalke This looks super, didn't know about this before. Will see if I can get link clickable!

**Comment by hindupuravinash** [comment]
Thanks to @lgalke there's a table now, which is listed in chronological order and is searchable by years/titles (and anything else too, but I found these two to be most helpful).
