### ISSUE TITLE
Paper introducing CGAN

### ISSUE THREAD

**Issue by Banus** [hindupuravinash/the-gan-zoo#2]
Hi @hindupuravinash, I noticed that for Conditional GANs (CGANs) a recent work is reported (https://arxiv.org/abs/1703.06029), but the method was already introduced in 2014 (https://arxiv.org/abs/1411.1784).
If you check the references in `arXiv:1703.06029,` you see the latter cited as previous work.

**Comment by hindupuravinash** [comment]
Yeah, I agree. Will fix it :)
