### ISSUE TITLE
Links to code

### ISSUE THREAD

**Issue by vlejd** [hindupuravinash/the-gan-zoo#21]
It would be super useful if you would provide links to corresponding github projects with implementation as well.

**Comment by lgalke** [comment]
Totally agree. I propose we start a new column in [gans.tsv](https://github.com/hindupuravinash/the-gan-zoo/blob/master/gans.tsv).

**Comment by hindupuravinash** [comment]
Yeah, agree! Will start adding my collection here.

**Comment by vlejd** [comment]
There are some nice links over here https://github.com/tdeboissiere/DeepLearningImplementations

**Comment by hindupuravinash** [comment]
Cool @vlejd , will check out and add original sources if available, else add third party implementations :)
