### ISSUE TITLE
group the lists by years

### ISSUE THREAD

**Issue by Jiewen2017** [hindupuravinash/the-gan-zoo#63]
Hi, dear,

I am thank you for the zoo. however, I can't seize some keywords I need when read the zoo to search a paper. Could you group it by years or category like 3D, image, etc.

My enligsh is poor and you can get my mean?

Thank you!

**Comment by hindupuravinash** [comment]
Hi, you can use the gans.tsv file in the repo for searching a particular paper by Name, title, year, github repo or the arxiv link of the research paper.

Here's the link: https://github.com/hindupuravinash/the-gan-zoo/blob/master/gans.tsv
