### ISSUE TITLE
The website Deep Hunt doesn't work

### ISSUE THREAD

**Issue by H-xie** [hindupuravinash/the-gan-zoo#67]
The website refered in the README.MD [Deep Hunt](https://deephunt.in) does not work.

The link skip to a URL named **https://medium.com/m/global-identity?redirectUrl=https%3A%2F%2Fdeephunt.in%2F**

Is the URL changed? What is the new one?

**Comment by hindupuravinash** [comment]
It's just the same, there were no issues when I checked. Hope it works for you now. Closing the issue until further reports
